Update LootHelper.cs
thomas-crane/KRelay pull request #3
Opened 2017-12-20 23:16 UTC by ouaklafoud

2017-12-22 01:18 UTC, thomas-crane commented
I won't get a chance to test this until later today, but the code looks fine so I should be able to merge this after testing.

2017-12-31 02:04 UTC, ouaklafoud commented
This let me know i left a dirk of cronus on the floor .... so it worth the look 🥇 
maybe you ll find out how to better state the item name, but for me it seems to work fine.. from time to time i have this error in the NEWTICK, UPDATE package

2018-01-01 22:35 UTC, ouaklafoud commented
I commented here and there the PluginUtils.Log of "Client received" , "Connected to remote host." and "Disconnected.", then I get no error displayed anymore ever from loot logs I added

2018-01-08 18:13 UTC, ouaklafoud commented
allows to load from external packets.xml

2018-01-09 00:32 UTC, thomas-crane commented
My apologies, I haven't had a chance to test this yet since I'm on holiday at the moment and only have access to a Mac. I've looked through the code and can't see any issues which might come up from testing, so I will probably just merge it anyway :smile: I can always revert it if there is an issue anyway.

2018-01-11 00:15 UTC, thomas-crane requested changes

2018-01-11 00:15 UTC, thomas-crane commented on Lib K Relay/GameData/GameData.cs
> +                    PluginUtils.Log("GameData", "loaded from file!");
Can this be a bit more descriptive, e.g. `Loaded packets from Packets.xml`?

2018-05-04 07:38 UTC, merged